#gradle:
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=true

loom_version=1.18-SNAPSHOT
chenille_version=0.22.1
vanniktech_version=0.37.0

#mod:
version=0.4.100
group=io.github.nottherealdeal

#publishing:
mavenCentralAutomaticPublishing=true
mavenCentralDeploymentValidation=VALIDATED

#compile:
loader_version=0.19.5
minecraft_version=26.3
fabric_api_version=0.161.0+26.3
cca_version=8.1.0
jei_version=31.9.0.56

#runtime:
modmenu_version=kyy7dbrZ
carpet_version=yt9oDFOj
spark_version=e3hsPc1o
sodium_version=v4PSXean